fixtures:
  repositories:
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    translate: "https://github.com/puppetlabs/puppetlabs-translate.git"
    firewall: "https://github.com/puppetlabs/puppetlabs-firewall.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
    mount_core:
      repo: https://github.com/puppetlabs/puppetlabs-mount_core.git
      puppet_version: ">= 6.0.0"
